/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import com.mycompany.projetolpooe1_paulalondero.dao.PersistenciaJPA;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Ferias;

/**
 *
 * @author paula
 */
public class TelaFerias extends javax.swing.JFrame {
    PersistenciaJPA jpa;

    /**
     * Creates new form TelaFerias
     */
    public TelaFerias() {
        initComponents();
        jpa = new PersistenciaJPA();
        carregarFerias();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblFuncionario = new javax.swing.JLabel();
        txtBuscaFuncionario = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstFerias = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Férias Cadastradas");

        lblFuncionario.setText("Funcionário:");

        txtBuscaFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaFuncionarioKeyReleased(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstFerias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnNovo)
                        .addGap(30, 30, 30)
                        .addComponent(btnEditar)
                        .addGap(61, 61, 61)
                        .addComponent(btnRemover))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncionario)
                    .addComponent(txtBuscaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        TelaCadastroFerias telaCadastroF
                = new TelaCadastroFerias(this, rootPaneCheckingEnabled);
        telaCadastroF.setVisible(true);

        carregarFerias();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Ferias feriasSel = lstFerias.getSelectedValue();
        if (feriasSel != null) {
        // Verificando se o funcionário já está atribuído corretamente a 'feriasSel'
        if (feriasSel.getFuncionario() != null) {
            // Criando uma nova tela de edição e passando os dados
            TelaCadastroFerias telaEdt = new TelaCadastroFerias(this, rootPaneCheckingEnabled);
            telaEdt.setFerias(feriasSel); // Passando o objeto Ferias para a tela de edição
            telaEdt.setVisible(true);
            
            // Atualizando a lista de férias após a edição
            carregarFerias();
        } else {
            JOptionPane.showMessageDialog(this, "Funcionário não encontrado para as férias selecionadas.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecione um item para editar.");
    }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
    Ferias feriasSel = lstFerias.getSelectedValue();
    if (feriasSel != null) {
        System.out.println("Funcionário: " + feriasSel.getFuncionario());
        try {
            jpa.conexaoAberta();

            // Confirmação de exclusão
            int delOp = JOptionPane.showConfirmDialog(this,
                    "Tem certeza que deseja remover " + feriasSel.getFuncionario().getNome() + "?");
            if (delOp == JOptionPane.YES_OPTION) {
                // Remover da persistência (base de dados)
                jpa.remover(feriasSel);

                // Atualizar a lista na interface gráfica após remoção
                carregarFerias();  // Recarrega a lista de férias

                JOptionPane.showMessageDialog(this, "Férias removidas com sucesso.");
            }

            jpa.fecharConexao();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao remover férias " + feriasSel + "\n" + e);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecione para remover");
    }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void txtBuscaFuncionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaFuncionarioKeyReleased
         if(txtBuscaFuncionario.getText().trim().isEmpty()){
            carregarFerias();
        } else{
            jpa.conexaoAberta();
            DefaultListModel modeloLista = new DefaultListModel();
            modeloLista.addAll(jpa.getFuncionarios(txtBuscaFuncionario.getText().trim()));
            System.out.println("Funcinários carregados: "+jpa.getFuncionarios(txtBuscaFuncionario.getText().trim()));
            lstFerias.setModel(modeloLista);

            jpa.fecharConexao();
        }
    }//GEN-LAST:event_txtBuscaFuncionarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFerias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFerias().setVisible(true);
            }
        });
    }

    public void carregarFerias() {
    jpa.conexaoAberta();

    DefaultListModel modeloLista = new DefaultListModel();
    // Carregar as férias (não apenas os funcionários)
    List<Ferias> feriasList = jpa.getFerias(); // Supondo que tenha um método para pegar as férias
    modeloLista.addAll(feriasList);
    lstFerias.setModel(modeloLista);

    jpa.fecharConexao();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<Ferias> lstFerias;
    private javax.swing.JTextField txtBuscaFuncionario;
    // End of variables declaration//GEN-END:variables
}
